### ISSUE TITLE
기본 레포지토리 세팅

### ISSUE THREAD

**Issue by woosukji** [osamhack2021/AI_WEB_POOL_YD#1]
- vue-cli 세팅
- 디렉토리 정리
- 기본 라이브러리 추가
- ?초기 개발환경 세팅용 (dependencies 추가한) Dockerfile 생성? ([참고](https://docs.github.com/en/codespaces/customizing-your-codespace/configuring-codespaces-for-your-project))

**Comment by somnisomni** [comment]
devcontainer.json은 이전 커밋에서 생성 완료했습니다. https://github.com/osamhack2021/AI_WEB_POOL_YD/commit/5c4f8e6a41abdb12651d585f5f7c1c4d7c64072c

Vue.js 프론트엔드는 초기 세팅은 다이렉트로 마스터 브랜치에 커밋했습니다. https://github.com/osamhack2021/AI_WEB_POOL_YD/commit/78f37f9a643a7196c30fda21670a74c366474043

현재 설치된 Vue.js 라이브러리는 Vuex, Vue-Router(, TypeScript, dart-sass 등)입니다.

이후 개발 진행 시 브랜칭하면서 진행합니다.
